name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.1.0
      with:
        version: 12.x

    - name: Install dependencies
      run: |
        composer install -o
        npm install

    - name: Build
      run: npm run build
    
    - name: Sync
      env:
        dest: 'threpsimyc@server161.web-hosting.com:/home/threpmyc/public_html/wp-content/themes/nebularwind/'
      run: |
        echo "${{secrets.DEPLOY_KEY}}"
        base64 -d
        sshpass -p ###### rsync -v 
        --delete 
        --recursive 
        --exclude=/.git/ 
        --exclude=.vscode 
        --exclude=node_modules -e ssh -p 21098 -o StrictHostKeyChecking=no . threpmyc@server161.web-hosting.com:${{env.dest}}
